StylesPath = .github/styles
MinAlertLevel = warning

# Tells Vale to use your custom vocabulary
Vocab = base

# Tells Vale which external package to download
Packages = Google

[*.md]
BasedOnStyles = Vale, Google
