[project]
site_name = "Engineer the docs"
extra_css = ["assets/stylesheets/custom.css"]

# Navigation
nav = [
    { "Home" = "index.md" },
    { "What is docs engineering?"= [
        {"Docs as code, DocOps, and docs engineering" = "introduction/docs-engineering-overview.md" }
    ]}
] 
    # { "Get started" = [
    #     {},
    #     {},
    #     {}
    # ]},
    # {"Information architecture" = [
    #     {},
    #     {}
    # ]},
    # {"Quality gates" = [
    #     {},
    #     {}
    # ]},
    # {"AgenticOps" = [
    #     {},
    #     {}  
    # ]},
    # {"Docs observability" = [
    #     {},
    #     {}  
    # ]}


[project.theme]
language = "en"
features = [
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.sections",
    "navigation.expand",
    "search.suggest",
    "search.highlight",
]

[markdown_extensions]
attr_list = true

# Light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "custom"
accent = "custom"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "custom"
accent = "custom"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"