[project]
site_name = "Engineer the docs"
extra_css = ["assets/stylesheets/custom.css"]

[project.theme]
language = "en"
features = [
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.sections",
    "navigation.expand",
    "search.suggest",
    "search.highlight",
]

# Light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

# Navigation
nav = [
    { "Home" = "index.md" },
    { "DaC overview"= "overview-dac.md" }
]